apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        components: web
    spec:
      containers:
        - name: client
          image: kaeyz/muliti-client
          ports:
            - containerPort: 3000